# Generated by Django 3.1.6 on 2021-02-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('access_url', models.CharField(max_length=200)),
                ('access_format', models.CharField(max_length=200)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('x_min', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('x_max', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('y_min', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('y_max', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('z_min', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('z_max', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('n_pix', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('f_min', models.FloatField()),
                ('f_max', models.FloatField()),
                ('f_sum', models.FloatField()),
                ('rel', models.FloatField(blank=True, null=True)),
                ('rms', models.FloatField()),
                ('w20', models.FloatField()),
                ('w50', models.FloatField()),
                ('ell_maj', models.FloatField()),
                ('ell_min', models.FloatField()),
                ('ell_pa', models.FloatField()),
                ('ell3s_maj', models.FloatField()),
                ('ell3s_min', models.FloatField()),
                ('ell3s_pa', models.FloatField()),
                ('kin_pa', models.FloatField(blank=True, null=True)),
                ('ra', models.FloatField(blank=True, null=True)),
                ('dec', models.FloatField(blank=True, null=True)),
                ('l', models.FloatField(blank=True, null=True)),
                ('b', models.FloatField(blank=True, null=True)),
                ('v_rad', models.FloatField(blank=True, null=True)),
                ('v_opt', models.FloatField(blank=True, null=True)),
                ('v_app', models.FloatField(blank=True, null=True)),
                ('err_x', models.FloatField()),
                ('err_y', models.FloatField()),
                ('err_z', models.FloatField()),
                ('err_f_sum', models.FloatField()),
                ('freq', models.FloatField(blank=True, null=True)),
                ('flag', models.IntegerField(blank=True, null=True)),
                ('unresolved', models.BooleanField()),
            ],
            options={
                'db_table': 'detection',
                'managed': False,
            },
        ),
    ]
