version: '3.5'

services:
  survey_web:
    image: survey_web
    container_name: survey_web
    build:
      context: web
    ports:
      - 8000:8000
    volumes:
      - ./web:/opt/services/survey_web/src
      - static_volume:/opt/services/survey_web/src/static
      - media_volume:/opt/services/survey_web/src/media
    networks:
      - sofiax_network

  sofiax_nginx:
    image: sofiax_nginx
    container_name: sofiax_nginx
    build:
      context: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl.conf:/config/nginx/ssl.conf
      - static_volume:/opt/services/survey_web/src/static
      - media_volume:/opt/services/survey_web/src/media
    depends_on:
      - survey_web
    networks:
      - sofiax_network

  sofiax_vo:
    image: sofiax_vo
    container_name: sofiax_vo
    build:
      context: vo
    env_file:
      - vo/vo.env
    ports:
      - 8080:8080
    networks:
      - sofiax_network
            
networks:
  sofiax_network:
    name: sofiax_network
    driver: bridge

volumes:
  static_volume:
  media_volume:
