version: '3.5'

services:
  db:
    build:
      context: db
    image: sofiax_db
    container_name: sofiax_db
    ports:
      - 5432:5432
    env_file:
      - vo/vo.env
    networks:
      - sofiax_network

  api:
    build:
      context: api
    image: sofiax_api
    container_name: sofiax_api
    command: init
    ports:
      - 8000:8000
    env_file: 
      - api/.env
    depends_on: 
      - db
    volumes:
      - ./api:/opt/services/sofiax_api/src
      - static_volume:/opt/services/sofiax_api/static
      - media_volume:/opt/services/sofiax_api/media
    networks:
      - sofiax_network

  vo:
    build:
      context: vo
    image: sofiax_vo
    container_name: sofiax_vo
    ports:
      - 8080:8080
    env_file:
      - vo/vo.env
    networks:
      - sofiax_network

  nginx:
    build:
      context: nginx
    image: sofiax_nginx
    container_name: sofiax_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/opt/services/sofiax_api/static
      - media_volume:/opt/services/sofiax_api/media
    depends_on:
      - api
      - vo
    networks:
      - sofiax_network
            
networks:
  sofiax_network:
    name: sofiax_network
    driver: bridge

volumes:
  static_volume:
  media_volume:
