version: '3.5'

services:
  survey_db:
    image: survey_db
    container_name: survey_db
    shm_size: '32gb'
    build:
      context: db/
      shm_size: '32gb'
    env_file:
      - db/psql.env
    ports:
      - 5432:5432
    volumes:
      - /data:/var/lib/postgresql/data
    networks:
      - survey_network

  survey_web:
    image: survey_web
    container_name: survey_web
    build:
      context: web
    ports:
      - 8001:8000
    volumes:
      - ./web:/opt/services/survey_web/src
      - static_volume:/opt/services/survey_web/src/static
      - media_volume:/opt/services/survey_web/src/media
    networks:
      - survey_network

  survey_nginx:
    image: nginx:latest
    container_name: survey_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/www:/var/www/certbot
      - ./nginx/certs/letsencrypt:/etc/letsencrypt
      - ./nginx/logs:/var/log/nginx
      - static_volume:/opt/services/survey_web/src/static
      - media_volume:/opt/services/survey_web/src/media
    networks:
      - survey_network

  survey_certbot:
    image: certbot/certbot:latest
    container_name: survey_certbot
    volumes:
      - ./nginx/certs/www:/var/www/certbot
      - ./nginx/certs/letsencrypt:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - survey_network

  survey_vo:
    image: survey_vo
    container_name: survey_vo
    build:
      context: vo
    env_file:
      - vo/vo.env
    volumes:
      - /var/gavo/state:/var/gavo/state
      - /var/gavo/cache:/var/gavo/cache
      - /var/gavo/tmp:/var/gavo/tmp
    ports:
      - 8080:8080
    networks:
      - survey_network

networks:
  survey_network:
    name: survey_network
    driver: bridge

volumes:
  static_volume:
  media_volume:
