version: '3.5'

services:
  sofiax_api:
    image: sofiax_api
    container_name: sofiax_api
    env_file: 
      - api/.env
    build:
      context: api
    volumes:
      - ./api:/opt/services/sofiax_api/src
      - static_volume:/opt/services/sofiax_api/static
      - media_volume:/opt/services/sofiax_api/media
    networks:
      - sofiax_network

  sofiax_nginx:
    image: sofiax_nginx
    container_name: sofiax_nginx
    build:
      context: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/opt/services/sofiax_api/static
      - media_volume:/opt/services/sofiax_api/media
    depends_on:
      - sofiax_api
    networks:
      - sofiax_network

  sofiax_vo:
    image: sofiax_vo
    container_name: sofiax_vo
    build:
      context: vo
    env_file:
      - vo/vo.env
    ports:
      - 8080:8080
    networks:
      - sofiax_network
            
networks:
  sofiax_network:
    name: sofiax_network
    driver: bridge

volumes:
  static_volume:
  media_volume:
