version: '3.5'

services:
  sofiax_web_app:
    image: sofiax_web_app
    container_name: sofiax_web_app
    env_file: 
      - web/.env
    build:
      context: web
    volumes:
      - ./web:/opt/services/sofia_web_app/src
      - static_volume:/opt/services/sofia_web_app/static
      - media_volume:/opt/services/sofia_web_app/media
    networks:
      - sofiax_network

  sofiax_nginx:
    image: sofiax_nginx
    container_name: sofiax_ngnix
    build:
      context: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/opt/services/sofia_web_app/static
      - media_volume:/opt/services/sofia_web_app/media
    depends_on:
      - sofiax_web_app
    networks:
      - sofiax_network

  sofiax_vo:
    image: sofiax_vo
    container_name: sofiax_vo
    build:
      context: vo
    env_file:
      - vo/vo.env
    ports:
      - 8080:8080
    networks:
      - sofiax_network
            
networks:
  sofiax_network:
    name: sofiax_network
    driver: bridge

volumes:
  static_volume:
  media_volume:
