# Generated by Django 3.1.6 on 2021-02-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cube', models.BinaryField(blank=True, null=True)),
                ('mask', models.BinaryField(blank=True, null=True)),
                ('moment0', models.BinaryField(blank=True, null=True)),
                ('moment1', models.BinaryField(blank=True, null=True)),
                ('moment2', models.BinaryField(blank=True, null=True)),
                ('channels', models.BinaryField(blank=True, null=True)),
                ('spectrum', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
