services:
  dingo_db:
    shm_size: '32gb'
    build:
       context: .
       shm_size: '32gb'
    image: dingo_db
    container_name: dingo_db
    ports:
      - 5434:5432
    volumes:
      - /data:/var/lib/postgresql/data